name: Lint

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: .go-version

      - name: Get golangci-lint version from Makefile
        id: golangci_lint_version
        run: echo version=$(grep "golangci/golangci-lint" Makefile | sed "s/^[^v0-9]*\(v[0-9]\.[0-9]*\).*/\1/") >> $GITHUB_OUTPUT

      - name: test
        run: echo ${{ steps.golangci_lint_version.outputs.version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: ${{ steps.golangci_lint_version.outputs.version }}
