name: Trivy Container Scanner
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: '0 */24 * * *'  

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        tag: ["latest", "${{ github.sha }}"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build an image from Dockerfile
        if: matrix.version != 'latest'
        run: |
          make image IMAGE_VERSION=${{ github.sha }}

      - name: Run Trivy vulnerability scanner in repo mode
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'ghcr.io/aokumasan/github-actions-sample:${{ matrix.version }}'
          ignore-unfixed: true
          format: 'sarif'
          output: 'results.sarif'
          severity: 'HIGH,CRITICAL'

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'results.sarif'
